services:
  - type: web
    name: backed-api-scan-uat
    runtime: python
    plan: free
    region: singapore
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --worker-connections 1000 --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 5
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/bq-key.json
      - key: APP_ENV
        value: uat
      - key: UAT_SHEETS_ONLY
        value: "true"
      - key: SCAN_FEATURE_ENABLED
        value: "false"
      - key: UAT_DATABASE_SPREADSHEET_ID
        value: 1RJcsrbWnGO7gMiq9bhBR4bA9Twh1NjqP6816dXOW9DI
